gitlab-ci merged to gather

diff --git a/pipeline/gitlab/.gitlab-ci.DockerfileBuilder.yml b/pipeline/gitlab/.gitlab-ci.DockerfileBuilder.yml
--- a/pipeline/gitlab/.gitlab-ci.DockerfileBuilder.yml
+++ b/pipeline/gitlab/.gitlab-ci.DockerfileBuilder.yml
@@ -209,6 +209,107 @@ variables:
     #   EOF
 
 
+.build_via_docker_image:
+  variables:
+    DOCKERFILE_NAME_: Dockerfile
+    BRANCH: main
+    ENV_FILE_: 
+    BUILD_PATH: /app/build/web
+  stage: build
+  rules:
+    - if: '( ( $CI_COMMIT_TAG =~ $GIT_TAG && $GIT_TAG != "" ) || ( $BRANCH == $CI_COMMIT_BRANCH && $BRANCH != "" ) )'
+  script:
+    - |
+      if [ "$CI_COMMIT_REF_PROTECTED" != "true" ]; then
+        echo "Error: You should run the action only on protected branches!!"
+        exit 1
+      fi
+    - cd $SRC_DIRECTORY_
+    - |
+      if [ -f "$ENV_FILE_" ]; then
+        echo "Copy .env file"
+        cp $ENV_FILE_ .env
+      fi
+
+    - echo "Building Docker image ${IMAGE_NAME_}:${IMAGE_TAG_}... from ${DOCKERFILE_NAME_}"
+    - docker build --network=host -t $CI_REGISTRY_IMAGE -f $DOCKERFILE_NAME_ .
+    
+    - echo "Creating build directory"
+    - mkdir -p ./build/
+    
+    - echo "Copying artifacts from image"
+    - docker create --name temp_container $CI_REGISTRY_IMAGE
+    - docker cp temp_container:/$BUILD_PATH/. ./build/ || true
+    - docker rm temp_container
+
+  artifacts:
+    paths:
+      - build/
+    expire_in: 1 hours
+
+
+
+.deploy_built_files:
+  variables:
+    SSH_PRIVATE_KEY_:
+    SSH_PORT_: 22
+    SERVER_IP_:
+    SERVER_USER_:
+    SERVER_PATH_:
+    BRANCH:
+  stage: deploy
+  rules:
+    - if: '( ( $CI_COMMIT_TAG =~ $GIT_TAG && $GIT_TAG != "" ) || ( $BRANCH == $CI_COMMIT_BRANCH && $BRANCH != "" ) )'
+  script:
+    - cd $SRC_DIRECTORY_
+    ## Get ready to send files to server
+    - mkdir -p ~/.ssh
+    - echo "$SSH_PRIVATE_KEY_" > ~/.ssh/id_edtemp
+    - chmod 600 ~/.ssh/id_edtemp
+    - ssh-keyscan -p $SSH_PORT_ $SERVER_IP_ >> ~/.ssh/known_hosts
+    - |
+      ssh -p $SSH_PORT_ -o StrictHostKeyChecking=no \
+          -o IdentityFile=~/.ssh/id_edtemp \
+          $SERVER_USER_@$SERVER_IP_ << EOF
+            mkdir -p ${SERVER_PATH_}
+      EOF
+    # - scp -P ${SSH_PORT_} -i ~/.ssh/id_edtemp -r ./build/* ${SERVER_USER_}@${SERVER_IP_}:${SERVER_PATH_}/
+    - rsync -e "ssh -p $SSH_PORT_ -i ~/.ssh/id_edtemp" -avz --delete ./build/* ${SERVER_USER_}@${SERVER_IP_}:${SERVER_PATH_}/
+
+## Old examples 
+
+# build_files:
+#   extends: .build_via_docker_image
+#   variables:
+#     DOCKERFILE_NAME_: Dockerfile
+#     BRANCH: main
+#     ENV_FILE_: 
+#     BUILD_PATH: /app/build/web
+
+
+# deploy:
+#   extends: .deploy_built_files
+#   needs: 
+#     - build_files
+#   variables:
+#     SSH_PRIVATE_KEY_: $SSH_PRIVATE_KEY
+#     SSH_PORT_: $SSH_PORT
+#     SERVER_IP_: $SERVER_IP
+#     SERVER_USER_: $SERVER_USER  
+#     SERVER_PATH_: $SERVER_PATH
+#     BRANCH: main
+
+
+
+
+
+
+
+
+
+
+
+
 
 
 ## Examples
